"""initial agent schema (ADR-005, ADR-008, ADR-009)

Autogenerated, then reviewed by hand: added the append-only grant on `decisions`, the
`policy_controls` row, and dropping the enum types on downgrade.

Revision ID: 0001
Revises:
Create Date: 2026-10-08 20:54:49.856629
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "customers",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    op.create_table(
        "policy_controls",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("breaker_tripped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("breaker_reset_by", sa.Text(), nullable=True),
        sa.Column("breaker_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sends_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.CheckConstraint("id = 1", name=op.f("ck_policy_controls_single_row")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_controls")),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("active_turn_id", sa.UUID(), nullable=True),
        sa.Column("turn_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["customers.id"], name=op.f("fk_conversations_user_id_customers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("owner_user_id", sa.Text(), nullable=False),
        sa.Column("charged_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "shipped", "delivered", "cancelled", name="fulfillment_status"),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("chargeback_open", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'delivered' OR delivered_at IS NOT NULL",
            name=op.f("ck_orders_delivered_has_time"),
        ),
        sa.CheckConstraint("charged_minor > 0", name=op.f("ck_orders_charged_positive")),
        sa.ForeignKeyConstraint(
            ["owner_user_id"], ["customers.id"], name=op.f("fk_orders_owner_user_id_customers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "AGENT_STEP",
                "AWAIT_APPROVAL",
                "APPROVED",
                "EXECUTING",
                "NEEDS_RECONCILIATION",
                "COMPLETED",
                "ESCALATED",
                name="run_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "refund_outcome",
            sa.Enum("none", "unknown", "confirmed", "rejected", name="refund_outcome"),
            server_default="none",
            nullable=False,
        ),
        sa.Column("claim_version", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("worker_id", sa.Text(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("action_id", sa.Text(), nullable=True),
        sa.Column("order_id", sa.Text(), nullable=True),
        sa.Column("amount_minor", sa.BigInteger(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("review_hash", sa.Text(), nullable=True),
        sa.Column("review_revision", sa.Integer(), server_default="0", nullable=False),
        sa.Column("review_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "approval_source", sa.Enum("policy", "reviewer", name="approval_source"), nullable=True
        ),
        sa.Column("approved_by", sa.Text(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column("canonical_payload", sa.Text(), nullable=True),
        sa.Column("first_send_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("presend_attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("escalated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("c01_flagged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("escalation_resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("escalation_resolved_by", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(refund_outcome = 'none') = (first_send_started_at IS NULL)",
            name=op.f("ck_runs_outcome_first_send"),
        ),
        sa.CheckConstraint(
            "approval_source IS DISTINCT FROM 'policy' OR approved_by IS NULL",
            name=op.f("ck_runs_policy_has_no_approver"),
        ),
        sa.CheckConstraint(
            "approval_source IS DISTINCT FROM 'reviewer' OR approved_by IS NOT NULL",
            name=op.f("ck_runs_reviewer_has_approver"),
        ),
        sa.CheckConstraint(
            "refund_outcome = 'none' OR (approved_at IS NOT NULL AND approval_source IS NOT NULL)",
            name=op.f("ck_runs_sent_was_approved"),
        ),
        sa.CheckConstraint(
            "status <> 'AWAIT_APPROVAL' OR review_deadline IS NOT NULL",
            name=op.f("ck_runs_review_has_deadline"),
        ),
        sa.CheckConstraint(
            "status <> 'ESCALATED' OR escalated_at IS NOT NULL",
            name=op.f("ck_runs_escalated_flagged"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('AGENT_STEP', 'AWAIT_APPROVAL', 'APPROVED') OR refund_outcome = 'none'",
            name=op.f("ck_runs_pre_send_none"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('APPROVED', 'EXECUTING', 'NEEDS_RECONCILIATION') OR approved_at IS NOT NULL",
            name=op.f("ck_runs_approved_has_time"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('COMPLETED', 'ESCALATED') OR refund_outcome <> 'unknown'",
            name=op.f("ck_runs_terminal_not_unknown"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('COMPLETED', 'ESCALATED') OR worker_id IS NULL",
            name=op.f("ck_runs_terminal_no_claim"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('EXECUTING', 'NEEDS_RECONCILIATION') OR refund_outcome = 'unknown'",
            name=op.f("ck_runs_uncertain_unknown"),
        ),
        sa.CheckConstraint(
            "amount_minor IS NULL OR amount_minor > 0", name=op.f("ck_runs_amount_positive")
        ),
        sa.CheckConstraint(
            "approved_by IS NULL OR approved_by <> user_id", name=op.f("ck_runs_no_self_approval")
        ),
        sa.CheckConstraint(
            "presend_attempts >= 0", name=op.f("ck_runs_presend_attempts_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_runs_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_runs_order_id_orders")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["customers.id"], name=op.f("fk_runs_user_id_customers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
        sa.UniqueConstraint("action_id", name=op.f("uq_runs_action_id")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_runs_idempotency_key")),
    )
    op.create_index(
        "ix_runs_capacity",
        "runs",
        ["user_id", "first_send_started_at"],
        unique=False,
        postgresql_where=sa.text("refund_outcome IN ('unknown', 'confirmed')"),
    )
    op.create_index("ix_runs_order_id", "runs", ["order_id"], unique=False)
    op.create_index(
        "ix_runs_policy_approved_by_user",
        "runs",
        ["user_id", "approved_at"],
        unique=False,
        postgresql_where=sa.text("approval_source = 'policy'"),
    )
    op.create_index(
        "ix_runs_policy_approved_global",
        "runs",
        ["approved_at"],
        unique=False,
        postgresql_where=sa.text("approval_source = 'policy'"),
    )
    op.create_index(
        "uq_runs_one_unfinished_per_conversation",
        "runs",
        ["conversation_id"],
        unique=True,
        postgresql_where=sa.text("status NOT IN ('COMPLETED', 'ESCALATED')"),
    )
    op.create_table(
        "decisions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("action_id", sa.Text(), nullable=True),
        sa.Column("stage", sa.Text(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column(
            "rule_ids",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("policy_version", sa.Text(), nullable=False),
        sa.Column("config_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("review_hash", sa.Text(), nullable=True),
        sa.Column("trace_id", sa.Text(), nullable=True),
        sa.Column("decided_by", sa.Text(), nullable=False),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "stage IN ('proposal', 'presend', 'reviewer_approve', 'reviewer_decline', 'review_expiry', 'escalation_resolution', 'conversation_escalation', 'breaker_trip', 'breaker_reset', 'kill_switch')",
            name=op.f("ck_decisions_known_stage"),
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_decisions_run_id_runs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
    )
    op.create_index("ix_decisions_decided_at", "decisions", ["decided_at"], unique=False)
    op.create_index("ix_decisions_run_id", "decisions", ["run_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_events_conversation_id_conversations"),
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_events_run_id_runs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(
        "ix_events_conversation_id_id", "events", ["conversation_id", "id"], unique=False
    )
    op.create_table(
        "run_order_lookups",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.Text(), nullable=False),
        sa.Column(
            "looked_up_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_run_order_lookups_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_order_lookups_run_id_runs")
        ),
        sa.PrimaryKeyConstraint("run_id", "order_id", name=op.f("pk_run_order_lookups")),
    )

    # ADR-009: the decision log is append-only for the application. The init script's
    # default privileges grant SELECT, INSERT, UPDATE (never DELETE/TRUNCATE) to agent_app;
    # take UPDATE back here. The runtime role doesn't own the table, so it can't re-grant.
    op.execute("REVOKE UPDATE, DELETE, TRUNCATE ON decisions FROM agent_app")

    # ADR-009: one policy_controls row; sends enabled, breaker not tripped.
    op.execute("INSERT INTO policy_controls (id, sends_enabled) VALUES (1, true)")


def downgrade() -> None:
    op.drop_table("run_order_lookups")
    op.drop_index("ix_events_conversation_id_id", table_name="events")
    op.drop_table("events")
    op.drop_index("ix_decisions_run_id", table_name="decisions")
    op.drop_index("ix_decisions_decided_at", table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(
        "uq_runs_one_unfinished_per_conversation",
        table_name="runs",
        postgresql_where=sa.text("status NOT IN ('COMPLETED', 'ESCALATED')"),
    )
    op.drop_index(
        "ix_runs_policy_approved_global",
        table_name="runs",
        postgresql_where=sa.text("approval_source = 'policy'"),
    )
    op.drop_index(
        "ix_runs_policy_approved_by_user",
        table_name="runs",
        postgresql_where=sa.text("approval_source = 'policy'"),
    )
    op.drop_index("ix_runs_order_id", table_name="runs")
    op.drop_index(
        "ix_runs_capacity",
        table_name="runs",
        postgresql_where=sa.text("refund_outcome IN ('unknown', 'confirmed')"),
    )
    op.drop_table("runs")
    op.drop_table("orders")
    op.drop_table("conversations")
    op.drop_table("policy_controls")
    op.drop_table("customers")
    # Autogenerate doesn't drop enum types; without this, upgrade after downgrade fails.
    for enum_name in ("run_status", "refund_outcome", "approval_source", "fulfillment_status"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
